### ISSUE TITLE
Congratulations! A few Questions.

### ISSUE THREAD

**Issue by nicholasmartin** [thePrintLabs/pressroom#2]
Hi guys,

First of all congratulations on a very exciting project! I'm a big fan of WordPress and think it's a great idea to extend it to work with the Baker Framework!

I would be very interested to hear more about your future plans. Specifically:

1) Support for paid issues and subscriptions end points?
2) The upcoming paid version of PressRoom and what it includes?
3) Android version ---> I'm guessing this is the Android Baker version?

We will be doing a series of videos explaining how people can get started in digital publishing without having to spend hundreds or thousands of bucks with the likes of Adobe, Mag+, PressPad, etc. and PressRoom could be a great candidate to include in these videos. Yes it's definitely a DIY solution but there are many people interested in this.

Once again job well done guys!

**Comment by nicholasmartin** [comment]
No one to answer questions?

**Comment by yumyo** [comment]
@MagLoftMagazines thanks so much for the greetings. We were very busy in pushing PressRoom Free forward and setting up the Pro service. The latter includes full support to iTunes in-App purchases for issues and subscriptions. Read more about the PRO version https://press-room.io/pressroom-pro-is-available-how-it-works/

You could also take a look at the [Latterly Magazine iOS App](https://itunes.apple.com/us/app/latterly-magazine/id960305443?mt=8) and website [http://latterlymagazine.com/](http://latterlymagazine.com/) for an example of a  real world implementation.

Android client version development still depends on user's request volume. Please contact us directly if you think there's room for collaboration on smart ideas ; )

**Comment by nicholasmartin** [comment]
Congratulations on your pro version. I'm certain a lot of Wordpress users will love being able to work from their CMS.

Let's stay in touch :)
