### ISSUE TITLE
Uploading to external services

### ISSUE THREAD

**Issue by pieterclaerhout** [thePrintLabs/pressroom#3]
Hi there, are there any plans to make Pressroom more modular so that the generated hpub can e.g. be uploading to different backends. We at Twixl media (twixlmedia.com) are working on supporting HPub on our Twixl Distribution Platform, and it would be great if there could be an integration with Pressroom.

In our current beta version the upload happens by means of an API call...

**Comment by pieterclaerhout** [comment]
What does it take to create a custom exporter in the latest release?

**Comment by yumyo** [comment]
@pieterclaerhout publishing hpub files via ftp/sftp could be supported in the near future but it isn't on our roadmap currently. We don't know what are your backend requirement but just as a tip, If you install PressRoom on your own server environment you'll still be able to symlink the hpub folder or setup a bash script to automate the transfer via rsync or scp.
