### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by lopesval** [thePrintLabs/pressroom#4]
Hello, when i activate P-2-P plugin with PressRoom active it triggers the following tryed with the Github version of Posts 2 Posts and also the one on wordpress repository. 
Thanks
Fatal error: Call to undefined function scb_init() in /home/afryk/public_html/com.afryk.newsdesk/wp-content/plugins/posts-to-posts/posts-to-posts.php on line 66

**Comment by yumyo** [comment]
Hi @lopesval please make sure you're using the latest version of PressRoom. It has been updated and it now comes  with the posts-2-posts lib bundled, so you won't need to install it as a separate plugin.

We was able to reproduce the issue you mentioned only if we try to install the naked lib [wp-lib-posts-to-posts](https://github.com/scribu/wp-lib-posts-to-posts) along with PressRoom.

Previous issues installing posts-2-posts from [https://github.com/scribu/wp-posts-to-posts](https://github.com/scribu/wp-posts-to-posts) or from [http://wordpress.org/plugins/posts-to-posts/](http://wordpress.org/plugins/posts-to-posts/) have been fixed.
